project:
  type: website
  output-dir: docs
  
execute:
  freeze: auto

website:
  title: "Metodebiblioteket"
  description: |
    Metodebibliotek
  repo-url: https://github.com/statisticsnorway/metodebibliotek

  navbar:
    background: primary
    logo: "pictures/logo_kule.jpg"
    logo-href: index.html
    left:
      - text: "Katalog"
        href: catalog.qmd
      - text: "Metodeområde"
        menu:
        - text: "Dataeditering"
          href: catalogue_edit.html
        - text: "Konfidensialitet"
          href: catalogue_conf.html

    right:
      - icon: github
        menu:
          - text: "Source Code"
            url:  https://github.com/statisticsnorway/metodebibliotek
          - text: "Report a Bug"
            url:  https://github.com/statisticsnorway/metodebibliotek/issues
    pinned: true

  sidebar:
    id: Katalog
    title: "Katalog"
    style: "docked"
    background: light
    search: false
    contents:
      - text: "Katalog"
        href: catalog.qmd
      - text: "Prosessmodell"
        href: prosess.qmd
        
format: 
  html: 
    theme: ssb.scss
    grid:
      sidebar-width: 250px
      margin-width: 250px
  
editor: source  


